apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-clients
  labels:
    app: iperf-client
spec:
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf-client
        image: sonyalevchenko/iperf3:latest
        command: ['/bin/sh', '-c', 'sleep infinity']
      terminationGracePeriodSeconds: 0