apiVersion: v1
kind: Service
metadata:
  name: iperf-server
spec:
  selector:
    app: iperf-server
  ports:
  - name: tcp-server
    protocol: TCP
    port: 5001
    targetPort: server
  - name: udp-server
    protocol: UDP
    port: 5001
    targetPort: server
