apiVersion: v1
kind: Service
metadata:
  name: iperf-server
spec:
  type: ClusterIP
  selector:
    app: iperf-server
  ports:
  - name: tcp-server
    protocol: TCP
    port: 12865
    targetPort: 12865

