apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-clients2
  labels:
    app: iperf-client
spec:
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf-client
        image: alectolytic/netperf:latest
        command: ['netperf','-H','10.216.6.184','-l','100','-t','TCP_RR','-v','2','--','-o','min_latency,mean_latency,max_latency,stddev_latency,transaction_rate']
        #-l 100 -t TCP_RR -v 2 -- -o min_latency,mean_latency,max_latency,stddev_latency,transaction_rate
      nodeSelector:
        netperf: client2
      terminationGracePeriodSeconds: 0
